apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-install
spec:
  steps:
    - args:
        - install
      command:
        - /usr/bin/mvn
      image: 'maven:3.6.3-openjdk-8-slim'
      name: build
      resources: {}
      workingDir: /workspace/output
  workspaces:
    - name: output