apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: pl-gitpull-mavenbuild1
spec: 
  workspaces: 
  - name: ws
  params: 
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
  - name: image
    type: string
    description: image to be build from the code
    
  tasks: 
  - name: fetch-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: ws
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: mvn-build
    taskRef:
      name: maven-install1
    runAfter:
      - fetch-repo
    workspaces:
    - name: output
      workspace: ws
  - name: build-image 
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.image)
    workspaces:
    - name: source
      workspace: ws
    runAfter:
      - mvn-build      
  - name: oc-create
    taskRef:
      name: oc-create
    workspaces:
    - name: output
      workspace: ws
    runAfter:
      - build-image
    
 