apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: pl-gitpull-mavenbuild
spec: 
  workspaces: 
  - name: source
  params: 
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
  tasks: 
  - name: fetch-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: mvn-build
    taskRef:
      name: maven-install
    runAfter:
      - fetch-repo
    workspaces:
    - name: output
      workspace: source
 