kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-sa
  
subjects:
- kind: ServiceAccount
  name: pl-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: ""
